[package]
name = "where_is"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive"] }
crossterm = "0.28.1"
ignore = "0.4.23"
inquire = "0.7.5"
rayon = "1.10.0"
